### ISSUE TITLE
Unexpected termination on USBTransferFragment summary

### ISSUE THREAD

**Issue by hewittc** [usb-tools/ViewSB#19]
Sometimes ViewSB will terminate unexpectedly with the following error in the presence of a packet fragment:

```Process CLIFrontend process:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/code/src/ViewSB/viewsb/ipc.py", line 124, in _subordinate_process_entry
    task.run()
  File "/code/src/ViewSB/viewsb/frontend.py", line 226, in run
    self.handle_communications()
  File "/code/src/ViewSB/viewsb/frontend.py", line 218, in handle_communications
    self.handle_incoming_packet(packet)
  File "/code/src/ViewSB/viewsb/frontends/cli.py", line 21, in handle_incoming_packet
    print(repr(packet))
  File "/code/src/ViewSB/viewsb/packet.py", line 304, in __repr__
    self.summarize(), data_summary, self.summarize_status())
  File "/code/src/ViewSB/viewsb/packet.py", line 588, in summarize
    return "ORPHANED {}B {}-{} transfer".format(len(self.data), self.direction.name, self.pid.name)
AttributeError: 'NoneType' object has no attribute 'name'
```

As a quick workaround to test ViewSB for the first time, I made the following change to check that `self.direction` and `self.pid` are defined first.

```diff --git a/viewsb/packet.py b/viewsb/packet.py
index b1145eb..e527704 100644
--- a/viewsb/packet.py
+++ b/viewsb/packet.py
@@ -585,7 +585,8 @@ class USBTransferFragment(USBTransfer):
     FIELDS = {'transfer_type'}
 
     def summarize(self):
-        return "ORPHANED {}B {}-{} transfer".format(len(self.data), self.direction.name, self.pid.name)
+        if self.direction and self.pid:
+            return "ORPHANED {}B {}-{} transfer".format(len(self.data), self.direction.name, self.pid.name)
 
 
 class USBBulkTransfer(USBDataTransfer):
```

**Comment by mndza** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
