### ISSUE TITLE
ImportError: cannot import name 'Flag'

### ISSUE THREAD

**Issue by xobs** [usb-tools/ViewSB#23]
I'm unable to run `viewsb.sh`.  I get the error `ImportError: cannot import name 'Flag'`:

```sh
(ViewSB) fomu@fomu-jig:~/ViewSB $ ./viewsb.sh
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/fomu/ViewSB/viewsb/__init__.py", line 2, in <module>
    from .analyzer import ViewSBAnalyzer
  File "/home/fomu/ViewSB/viewsb/analyzer.py", line 12, in <module>
    from .decoders import *
  File "/home/fomu/ViewSB/viewsb/decoders/__init__.py", line 4, in <module>
    from .classes import *
  File "/home/fomu/ViewSB/viewsb/decoders/classes/cdc.py", line 7, in <module>
    from ..standard_descriptors import GetClassSpecificDescriptorRequest
  File "/home/fomu/ViewSB/viewsb/decoders/standard_descriptors.py", line 12, in <module>
    from .standard_requests import GetDescriptorRequest
  File "/home/fomu/ViewSB/viewsb/decoders/standard_requests.py", line 14, in <module>
    from ..packet import USBControlTransfer
  File "/home/fomu/ViewSB/viewsb/packet.py", line 14, in <module>
    from enum import Flag, auto
ImportError: cannot import name 'Flag'
(ViewSB) fomu@fomu-jig:~/ViewSB $ 
```

Maybe the `enum` module doesn't work on a Raspberry Pi?

```sh
(ViewSB) fomu@fomu-jig:~/ViewSB $ pip install enum
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting enum
  Downloading https://files.pythonhosted.org/packages/02/a0/32e1d5a21b703f600183e205aafc6773577e16429af5ad3c3f9b956b07ca/enum-0.4.7.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/fomu/ViewSB/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gedcw2vw/enum/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gedcw2vw/enum/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-gedcw2vw/enum/pip-egg-info
         cwd: /tmp/pip-install-gedcw2vw/enum/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/fomu/ViewSB/local/lib/python3.5/site-packages/setuptools/__init__.py", line 18, in <module>
        import setuptools.version
      File "/home/fomu/ViewSB/local/lib/python3.5/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/fomu/ViewSB/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 33, in <module>
        import platform
      File "/usr/lib/python3.5/platform.py", line 117, in <module>
        import sys, os, re, subprocess
      File "/usr/lib/python3.5/subprocess.py", line 50, in <module>
        import signal
      File "/usr/lib/python3.5/signal.py", line 4, in <module>
        from enum import IntEnum as _IntEnum
    ImportError: cannot import name 'IntEnum'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(ViewSB) fomu@fomu-jig:~/ViewSB $
```

**Comment by ktemkin** [comment]
Looks like `enum.Flag` was first implemented in Python 3.6. I don't think we currently have a real stance on how-many-python-versions-back we're supporting, so I don't know this is something worth working around on our side.

That said, will your environment allow you to upgrade to a newer Python version?
