### ISSUE TITLE
run “viewsb openvizsla cli" error. why?

### ISSUE THREAD

**Issue by wdodo** [usb-tools/ViewSB#3]
FPGA: Bitstream timestamp 2014/11/10 16:31:07
FPGA: sending configuration bitstream
FPGA: CRC OK
FPGA: configured
Traceback (most recent call last):
  File "/usr/local/bin/viewsb", line 11, in <module>
    load_entry_point('viewsb==0.0.1', 'console_scripts', 'viewsb')()
  File "/usr/local/lib/python3.6/dist-packages/viewsb-0.0.1-py3.6.egg/viewsb/commands/viewsb.py", line 110, in main
    analyzer.run()
  File "/usr/local/lib/python3.6/dist-packages/viewsb-0.0.1-py3.6.egg/viewsb/analyzer.py", line 167, in run
    self.run_analysis_iteration()
  File "/usr/local/lib/python3.6/dist-packages/viewsb-0.0.1-py3.6.egg/viewsb/analyzer.py", line 132, in run_analysis_iteration
    self.process_analysis_queue()
  File "/usr/local/lib/python3.6/dist-packages/viewsb-0.0.1-py3.6.egg/viewsb/analyzer.py", line 78, in process_analysis_queue
    handled = decoder.handle_packet(packet)
  File "/usr/local/lib/python3.6/dist-packages/viewsb-0.0.1-py3.6.egg/viewsb/decoder.py", line 75, in handle_packet
    self.consume_packet(packet)
  File "/usr/local/lib/python3.6/dist-packages/viewsb-0.0.1-py3.6.egg/viewsb/decoders/grouping.py", line 89, in consume_packet
    self._consume_token_packet(packet)
  File "/usr/local/lib/python3.6/dist-packages/viewsb-0.0.1-py3.6.egg/viewsb/decoders/grouping.py", line 50, in _consume_token_packet
    new_packet = USBTokenPacket(crc5=crc5, **fields)
  File "/usr/local/lib/python3.6/dist-packages/viewsb-0.0.1-py3.6.egg/viewsb/packet.py", line 72, in __init__
    self.validate()
  File "/usr/local/lib/python3.6/dist-packages/viewsb-0.0.1-py3.6.egg/viewsb/packet.py", line 284, in validate
    self.direction = self.pid.direction().name
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by ktemkin** [comment]
Hey! Sorry about that; a bunch of the OpenVizsla work was sitting on a branch in my fork (. I've just PR'd those issues over; so hopefully they'll be in master within a day, or so. :)

For reference, the branch is: 
https://github.com/ktemkin/ViewSB/tree/openvizsla_filters

**Comment by ktemkin** [comment]
This is in master; so I'm going to close this -- feel free to comment if you're still having issues and we can re-open. :)
